### ISSUE TITLE
Fertilizer Maker does not generate any natural gas

### ISSUE THREAD

**Issue by Truinto** [Nightinggale/ONI-mods#3]
https://github.com/Nightinggale/ONI-mods/blob/aa1375e2b939dfabe41c2778ffcdf4aa650123ff/src/PipedOutput/Source/Refinement.cs#L76

Not sure what causes this, as the implementation seems fine.
Maybe the line should be like this:
`converter.outputElements = converter.outputElements.Append(new ElementConverter.OutputElement(emitter.emitRate, SimHashes.Methane, emitter.temperature));`

**Comment by Nightinggale** [comment]
It turned out that the issue was that the memory allocated to the outputElements array is fixed and Append doesn't add more memory. Adding the gas output didn't do anything because it just silently vanished due to not having memory to store the data. Now expand the allocated memory and then add the gas to the newly added index.
